### ISSUE TITLE
Error parse name project elixir

### ISSUE THREAD

**Issue by krlsdu** [snyk/snyk-hex-plugin#20]
`
snyk -d test
  snyk test <ref *1> { _: [ [Circular *1] ], debug: true } +0ms
  snyk-hex-plugin running "mix -v" +0ms
  snyk-hex-plugin running "mix -v" +8ms
  snyk-hex-plugin Sub process stderr:  +435msir_synk project dir
  snyk-hex-plugin mix version:  Erlang/OTP 24 [erts-12.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Mix 1.13.3 (compiled with Erlang/OTP 24)
 +0ms
  snyk-hex-plugin running "mix read.mix /home/carlos/tmp/example_elixir_synk" +3ms
  snyk-hex-plugin Sub process stderr:  +7ms
  snyk-hex-plugin Error running "mix read.mix /home/carlos/tmp/example_elixir_synk", exit code: 1 +934ms
  snyk-hex-plugin Error parsing manifest file on /home/carlos/tmp/example_elixir_synk Compiling 16 files (.ex)
Generated snyk app
 +0ms
Error: 
Testing /home/carlos/tmp/example_elixir_synk...

Error parsing manifest file on /home/carlos/tmp/example_elixir_synk
    at test (/home/carlos/.asdf/installs/nodejs/16.6.1/.npm/lib/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/commands/test/index.ts:238:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runCommand (/home/carlos/.asdf/installs/nodejs/16.6.1/.npm/lib/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:53:25)
    at main (/home/carlos/.asdf/installs/nodejs/16.6.1/.npm/lib/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/main.ts:317:11)
    at /home/carlos/.asdf/installs/nodejs/16.6.1/.npm/lib/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/index.ts:11:3
    at Object.callHandlingUnexpectedErrors (/home/carlos/.asdf/installs/nodejs/16.6.1/.npm/lib/node_modules/snyk/dist/cli/webpack:/snyk/src/lib/unexpected-error.ts:28:5)

`

**Comment by coreyti** [comment]
@krlsdu , if you are/were using `asdf`, take a look at [my comment](https://github.com/snyk/mix-parser/issues/10#issuecomment-2181772530) in Snyk's `mix-parser` library.
